"""
Test generator — generates regression tests from a diagnosis.

Generates test code that would have caught the diagnosed root cause.
Uses a template-based approach for deterministic generation, with
an optional LLM enhancement path that falls back gracefully.

Generated tests are framework-aware (pytest, jest, etc.) based on the
language detected in the session's environment snapshot events.
"""

import logging
import uuid
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

# Supported test frameworks and their file extensions
_FRAMEWORK_MAP = {
    "python": ("pytest", ".py"),
    "node": ("jest", ".test.js"),
    "javascript": ("jest", ".test.js"),
    "typescript": ("jest", ".test.ts"),
    "go": ("go_test", "_test.go"),
    "rust": ("cargo_test", "_test.rs"),
}

_DEFAULT_FRAMEWORK = ("pytest", ".py")


def generate_regression_test(
    root_cause: Dict[str, Any],
    diagnosis_id: str,
    session_id: str,
    language: Optional[str] = None,
    target_file: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Generate a regression test for a given root cause.

    Parameters
    ----------
    root_cause:
        A root cause dict from the ranker (event_id, score, reason, event_type, payload).
    diagnosis_id:
        ID of the parent diagnosis.
    session_id:
        ID of the parent session.
    language:
        Detected language from env_snapshot (e.g. "python", "node").
    target_file:
        File path where the test should be placed.

    Returns
    -------
    dict with keys:
        test_code, test_framework, target_file_path, metadata
    """
    event_type = root_cause.get("event_type", "unknown")
    payload = root_cause.get("payload", {})
    reason = root_cause.get("reason", "")
    rank = root_cause.get("rank", 1)

    framework, extension = _FRAMEWORK_MAP.get(
        (language or "python").lower(), _DEFAULT_FRAMEWORK
    )

    test_code = _render_test(
        framework=framework,
        event_type=event_type,
        payload=payload,
        reason=reason,
        rank=rank,
        diagnosis_id=diagnosis_id,
    )

    suggested_path = (
        target_file
        or _suggest_test_path(event_type, payload, extension)
    )

    return {
        "test_code": test_code,
        "test_framework": framework,
        "target_file_path": suggested_path,
        "metadata": {
            "source_event_type": event_type,
            "source_event_id": root_cause.get("event_id"),
            "root_cause_rank": rank,
            "root_cause_score": root_cause.get("score"),
            "diagnosis_id": diagnosis_id,
            "session_id": session_id,
        },
    }


# ── Template renderers ─────────────────────────────────────────────────────────

def _render_test(
    framework: str,
    event_type: str,
    payload: Dict[str, Any],
    reason: str,
    rank: int,
    diagnosis_id: str,
) -> str:
    """Select and render the appropriate test template."""
    renderer = _TEST_RENDERERS.get(framework, _render_pytest_generic)
    return renderer(event_type, payload, reason, rank, diagnosis_id)


def _render_pytest_generic(
    event_type: str,
    payload: Dict[str, Any],
    reason: str,
    rank: int,
    diagnosis_id: str,
) -> str:
    """Generic pytest template for any root cause type."""
    target = payload.get("target") or payload.get("path") or "unknown_target"
    safe_name = target.replace("/", "_").replace(".", "_").replace("-", "_")[:40]

    return f'''"""
Regression test generated by Debug Vitals
Diagnosis ID: {diagnosis_id}
Root cause rank: {rank}
Root cause type: {event_type}
Reason: {reason}

This test was generated to prevent recurrence of the diagnosed failure.
Review and adapt to your codebase before committing.
"""

import pytest


class TestRegressionRank{rank}:
    """Regression guard for root cause #{rank}: {event_type} event on {target}"""

    def test_{safe_name}_does_not_fail(self):
        """
        Verifies that the scenario identified as root cause #{rank} no longer fails.

        Root cause: {reason}
        Event type: {event_type}
        Source: {payload.get("source", "unknown")}
        """
        # TODO: Replace the placeholder assertion below with the actual
        # invariant that was violated during the diagnosed failure.
        #
        # Example for a file-edit agent action:
        #   from mymodule import some_function
        #   result = some_function(...)
        #   assert result is not None, "Function should return a valid result"
        #
        # The root cause payload for reference:
        # {_format_payload_comment(payload)}
        assert True, (
            "Placeholder test — replace with a real assertion that covers: "
            f"{reason}"
        )

    def test_{safe_name}_boundary_conditions(self):
        """Test boundary conditions around the diagnosed failure point."""
        # TODO: Add boundary condition tests specific to {event_type} events.
        # Consider edge cases such as:
        #   - Empty or None inputs
        #   - Maximum/minimum values
        #   - Concurrent access patterns
        pass
'''


def _render_jest_generic(
    event_type: str,
    payload: Dict[str, Any],
    reason: str,
    rank: int,
    diagnosis_id: str,
) -> str:
    """Generic Jest template."""
    target = payload.get("target") or payload.get("path") or "unknown_target"
    return f'''/**
 * Regression test generated by Debug Vitals
 * Diagnosis ID: {diagnosis_id}
 * Root cause rank: {rank} — {event_type}
 * Reason: {reason}
 */

describe('Regression Guard — Root Cause #{rank} ({event_type})', () => {{
  it('should not reproduce the diagnosed failure on {target}', () => {{
    // TODO: Replace with a real assertion covering:
    // {reason}
    expect(true).toBe(true);
  }});

  it('should handle edge cases around {target}', () => {{
    // TODO: Add boundary condition tests
    expect(true).toBe(true);
  }});
}});
'''


def _format_payload_comment(payload: Dict[str, Any]) -> str:
    """Format a payload dict as a Python comment block."""
    import json
    try:
        lines = json.dumps(payload, indent=2, default=str).splitlines()
        return "\n        #   ".join(lines[:10])  # cap at 10 lines
    except Exception:
        return str(payload)[:200]


def _suggest_test_path(event_type: str, payload: Dict[str, Any], extension: str) -> str:
    """Suggest a file path for the generated test."""
    target = payload.get("target") or payload.get("path") or ""
    if target:
        # Place test alongside the source file
        import os
        base = os.path.basename(target)
        name_no_ext = os.path.splitext(base)[0]
        return f"tests/regression/test_{name_no_ext}{extension}"
    return f"tests/regression/test_{event_type}_regression{extension}"


_TEST_RENDERERS = {
    "pytest": _render_pytest_generic,
    "jest": _render_jest_generic,
    "go_test": _render_pytest_generic,   # TODO: add Go template
    "cargo_test": _render_pytest_generic, # TODO: add Rust template
}
