"""
Diagnosis ORM model.
Stores the result of a diagnostic run on a session, including ranked root causes
and the LLM-generated (or template-generated) explanation.
"""

import uuid
from datetime import datetime
from typing import Optional

from sqlalchemy import String, DateTime, Text, Float, Integer, Boolean, ForeignKey, func
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models import Base


class Diagnosis(Base):
    __tablename__ = "diagnoses"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    session_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("diagnostic_sessions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Status of the diagnosis run
    status: Mapped[str] = mapped_column(
        String(32), nullable=False, default="pending", index=True
    )

    # Ordered list of ranked root cause objects (JSON array)
    # Each element: { "event_id": ..., "score": float, "reason": str, "rank": int }
    root_causes: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True)

    # Natural language explanation — may be LLM-generated or template-based
    explanation: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Was the explanation generated by LLM or the fallback template engine?
    explanation_source: Mapped[Optional[str]] = mapped_column(
        String(32), nullable=True
    )  # "llm" | "template" | None

    # The correlation graph edges, serialized for later re-use in verification
    graph_snapshot: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)

    # How many events were analysed in this run
    events_analysed: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    completed_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Duration in milliseconds
    duration_ms: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    # Relationship
    session: Mapped["DiagnosticSession"] = relationship(  # type: ignore[name-defined]
        "DiagnosticSession", back_populates="diagnoses"
    )

    def __repr__(self) -> str:
        return (
            f"<Diagnosis id={self.id} status={self.status} session={self.session_id}>"
        )
