"use client";

import { use, useState } from "react";
import { DEMO_SCENARIOS, DEFAULT_SCENARIO_ID, type ScenarioId } from "@/lib/demoData";
import { CausalChain } from "@/components/shared/CausalChain";
import { EvidenceBlocks } from "@/components/shared/EvidenceBlocks";

const CONFIDENCE_BADGE: Record<string, string> = {
  LOW: "badge badge-warning", MEDIUM: "badge badge-warning", HIGH: "badge badge-success",
};

// ── Reusable card wrapper ──────────────────────────────────────────
function Card({ children, style }: { children: React.ReactNode; style?: React.CSSProperties }) {
  return (
    <div style={{
      background: "#FFFFFF", border: "1px solid #D8E4E4", borderRadius: 12,
      boxShadow: "2px 2px 8px rgba(166,190,190,0.25), -1px -1px 4px rgba(255,255,255,0.8)",
      ...style,
    }}>
      {children}
    </div>
  );
}

export default function DiagnosisPage({ params }: { params: Promise<{ sessionId: string }> }) {
  const { sessionId } = use(params);
  const scenarioId = sessionId.replace("demo-", "") as ScenarioId;
  const scenario = DEMO_SCENARIOS[scenarioId] ?? DEMO_SCENARIOS[DEFAULT_SCENARIO_ID];

  const [verified, setVerified]     = useState(false);
  const [verifying, setVerifying]   = useState(false);
  const [showReg, setShowReg]       = useState(false);
  const [regDone, setRegDone]       = useState(false);

  function runVerification() {
    setVerifying(true);
    setTimeout(() => { setVerifying(false); setVerified(true); }, 1800);
  }

  const REGRESSION_TEST = `// regression: ${scenarioId}
// auto-generated by AgentDoctor · ${new Date().toISOString().slice(0, 10)}

import { readFileSync } from "fs";

test("runtime satisfies engines.node requirement", () => {
  const pkg = JSON.parse(readFileSync("package.json", "utf8"));
  const required = pkg.engines?.node ?? ">=0";
  const actual = process.versions.node;
  expect(semverSatisfies(actual, required)).toBe(true);
});`;

  return (
    <main className="page-content">

      {/* Page header */}
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 24 }}>
        <span className="t-section">Diagnosis</span>
        <span style={{ fontFamily: "var(--font-jb-mono), monospace", fontSize: 11, color: "#9AABAB" }}>
          CASE <span style={{ color: "#4B85BE", fontWeight: 600 }}>#{sessionId.slice(0, 4).toUpperCase()}</span>
        </span>
      </div>

      <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>

        {/* 1. Failure banner */}
        <div className="surface-failure" style={{ padding: "16px 20px" }}>
          <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 8 }}>
            <span className="badge badge-failure">● Failure Active</span>
          </div>
          <h1 style={{ fontSize: 17, fontWeight: 700, color: "#1C2222", lineHeight: 1.4 }}>
            {scenario.failureTitle}
          </h1>
        </div>

        {/* 2+3. Root cause + confidence */}
        <Card style={{ padding: "20px 22px" }}>
          <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 14 }}>
            <span className="t-section" style={{ color: "#718484" }}>Root Cause</span>
            <span className={CONFIDENCE_BADGE[scenario.confidence]}>{scenario.confidence} confidence</span>
          </div>
          <p style={{ fontSize: 17, fontWeight: 600, color: "#1C2222", lineHeight: 1.55, maxWidth: 580 }}>
            {scenario.rootCause}
          </p>
        </Card>

        {/* 4. Causal chain */}
        <Card style={{ padding: "20px 22px" }}>
          <span className="t-section" style={{ display: "block", marginBottom: 18 }}>Causal Chain</span>
          <CausalChain steps={scenario.causalChain} />
        </Card>

        {/* 5. Evidence */}
        <Card style={{ padding: "20px 22px" }}>
          <span className="t-section" style={{ display: "block", marginBottom: 18 }}>Evidence</span>
          <EvidenceBlocks items={scenario.evidence} />
        </Card>

        {/* 6+7. Affected + next step */}
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 14 }}>
          <Card style={{ padding: "18px 20px" }}>
            <span className="t-section" style={{ display: "block", marginBottom: 14 }}>Affected Components</span>
            {scenario.affectedComponents.map((c) => (
              <div key={c} style={{ display: "flex", alignItems: "baseline", gap: 8, marginBottom: 7 }}>
                <span style={{ fontFamily: "var(--font-jb-mono), monospace", fontSize: 11, color: "#DB2424", flexShrink: 0 }}>×</span>
                <span style={{ fontFamily: "var(--font-jb-mono), monospace", fontSize: 12, color: "#718484" }}>{c}</span>
              </div>
            ))}
          </Card>
          <Card style={{ padding: "18px 20px" }}>
            <span className="t-section" style={{ display: "block", marginBottom: 14 }}>Next Step</span>
            <p style={{ fontSize: 13, color: "#718484", lineHeight: 1.65 }}>{scenario.suggestedNextStep}</p>
          </Card>
        </div>

        {/* 8. Actions */}
        <Card style={{ padding: "20px 22px" }}>
          <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>
            {!verified && (
              <button className={`btn ${verifying ? "btn-secondary" : "btn-primary"}`}
                onClick={runVerification} disabled={verifying}>
                {verifying ? "Running verification…" : "Run verification"}
              </button>
            )}
            {verified && !showReg && (
              <button className="btn btn-secondary"
                onClick={() => { setShowReg(true); setTimeout(() => setRegDone(true), 1400); }}>
                Generate regression test
              </button>
            )}
            {verified && (
              <span className="badge badge-success" style={{ alignSelf: "center" }}>● Verified</span>
            )}
          </div>

          {/* Verification result */}
          {verified && (
            <div style={{ marginTop: 20, paddingTop: 20, borderTop: "1px solid #E8F0F0" }}>
              <span className="t-section" style={{ display: "block", marginBottom: 14, color: "#2BAB60" }}>Verification Complete</span>
              <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: 12, marginBottom: 14 }}>
                <div style={{ background: "rgba(219,36,36,0.05)", border: "1px solid rgba(219,36,36,0.15)", borderRadius: 8, padding: "12px 14px" }}>
                  <p style={{ fontSize: 9, fontWeight: 700, letterSpacing: "0.1em", textTransform: "uppercase", color: "#9AABAB", marginBottom: 8 }}>Control</p>
                  <p style={{ fontFamily: "var(--font-jb-mono), monospace", fontSize: 12, color: "#1C2222", marginBottom: 4 }}>{scenario.verification.control.label}</p>
                  <p style={{ fontFamily: "var(--font-jb-mono), monospace", fontSize: 11, color: "#DB2424" }}>{scenario.verification.control.result}</p>
                </div>
                <div style={{ background: "rgba(43,171,96,0.05)", border: "1px solid rgba(43,171,96,0.15)", borderRadius: 8, padding: "12px 14px" }}>
                  <p style={{ fontSize: 9, fontWeight: 700, letterSpacing: "0.1em", textTransform: "uppercase", color: "#9AABAB", marginBottom: 8 }}>Experiment</p>
                  <p style={{ fontFamily: "var(--font-jb-mono), monospace", fontSize: 12, color: "#1C2222", marginBottom: 4 }}>{scenario.verification.experiment.label}</p>
                  <p style={{ fontFamily: "var(--font-jb-mono), monospace", fontSize: 11, color: "#2BAB60" }}>{scenario.verification.experiment.result}</p>
                </div>
              </div>
              <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
                <span className="t-section">Confidence</span>
                <span style={{ fontFamily: "var(--font-jb-mono), monospace", fontSize: 11, color: "#718484" }}>{scenario.verification.confidenceBefore}</span>
                <span style={{ fontFamily: "var(--font-jb-mono), monospace", fontSize: 13, color: "#9AABAB" }}>→</span>
                <span style={{ fontFamily: "var(--font-jb-mono), monospace", fontSize: 11, color: "#2BAB60", fontWeight: 600 }}>{scenario.verification.confidenceAfter}</span>
              </div>
            </div>
          )}

          {/* Regression guard */}
          {showReg && (
            <div style={{ marginTop: 20, paddingTop: 20, borderTop: "1px solid #E8F0F0" }}>
              <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 12 }}>
                <span className="badge badge-accent">Regression Guard</span>
              </div>
              <p style={{ fontSize: 13, color: "#718484", marginBottom: 14 }}>One targeted test — reproduces this exact failure.</p>
              <pre style={{
                fontFamily: "var(--font-jb-mono), monospace", fontSize: 12, lineHeight: 1.75, color: "#1C2222",
                background: "#F2F6F6", border: "1px solid #D8E4E4", borderRadius: 8, padding: "16px 18px",
                overflowX: "auto",
                boxShadow: "inset 2px 2px 5px rgba(166,190,190,0.3), inset -1px -1px 3px rgba(255,255,255,0.8)",
              }}>{REGRESSION_TEST}</pre>
              {regDone && <p style={{ fontFamily: "var(--font-jb-mono), monospace", fontSize: 11, color: "#2BAB60", marginTop: 12 }}>✓ generated and passed</p>}
            </div>
          )}
        </Card>
      </div>
    </main>
  );
}
